### PR TITLE
Complete refactoring. Let's call that 3.0?

### PR DESCRIPTION
**Pull request by Guekka**
The biggest change is probably the introduction of ``transform_archive``
The new design, using ``saver``'s, is arguably not the best. Maybe the ``saver``s should take ownership of the archive they are saving, instead of storing a reference.

### CODE REVIEW

**Comment by deorder** [comment]
Thanks. I will have a look.

**Comment by Al12rs** [comment]
What is the main goal of this refactor?

**Comment by Guekka** [comment]
@Al12rs The main goal is to allow archive transformation directly in memory easily. This is mainly done by the function ``transform_archive``

**Comment by Karandra** [comment]
Wait, G'k, it's you?

**Comment by Guekka** [comment]
Yes? (you're fast)

**Comment by Karandra** [comment]
Nothing. I'm just going to remember your name here.

**Comment by Al12rs** [comment]
Any examples on practical applications using transform?

**Comment by Guekka** [comment]
Sure
```cpp
libbsarch::transform_archive("source.bsa", "target.bsa", [](const fs::path &relative_path, extracted_data &&blob)
{
  //Detect the filetype according to the extension (an example of relative path may be "meshes/test.nif")
  //Load and process the file. For example with NIF library:
  NifFile nif;
  std::stringstream stream(static_cast<char*>(blob.get_buffer()), blob.get_size());
  nif.Load(stream);
  //Process the file
  //Return the result as a std::vector<std::byte>
});
```

**Comment by Guekka** [comment]
That said, I mainly use it for CAO

**Comment by Al12rs** [comment]
Nice! Then I guess this could be used to preview textures inside archives for example?

**Comment by Guekka** [comment]
> Nice! Then I guess this could be used to preview textures inside archives for example?

That's not the intended use case. If you simply want to *view* the content without *transforming* it, you can just use something like
```cpp
libbsarch::bsa bsa;
bsa.load("source.bsa");
for(const auto& path : bsa.list_files())
{
  const auto data = bsa.extract_to_memory(path);
  //Do something with data
}
//Data buffer is automatically deleted when going out of scope (RAII), so be sure to save it if necessary
```

**Comment by Al12rs** [comment]
Understood, thanks for the explanation!

**Comment by deorder** [comment]
As soon as everyone agrees and we can ensure nothing will break, I will merge it to master and merge it with my "reorganize" branch. The "reorganize" branch will make the "C89" interface usable again next to the improved C++ one and I added back the Delphi project that can be used to build the actual DLL (slightly modified bsarch) that somehow got lost in the process.

**Comment by Al12rs** [comment]
I have no qualms with the changes that were listed but I didn't do any testing at all

**Pull request closed without merging**
